### ISSUE TITLE
v1.5-beta: too much debug information when running ./LibreQoS.py (without debug parameters)

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#513]
There is too much output when running/reloading using command `./LibreQoS.py` (without --debug param).

This is debug:
`Warning: sch_htb: quantum of class 800ED is big. Consider r2q change`

Also this:
`Running Python Version 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]`

Also this (?):
```
Bin 0 =  {}
Bin 1 =  {}
Bin 2 =  {}
Bin 3 =  {}
Bin 4 =  {}
Bin 5 =  {}
Bin 6 =  {}
Bin 7 =  {}
```

Also this (sumarized is enough for non-debug):
```
        TC commands:    8.5 seconds
        XDP setup:       0 seconds
        XDP filters:     0.3076 seconds
```

Also this (dont print all the checks when --debug but when lqosd is not running always print an error):
`lqosd is running`

**Comment by interduo** [comment]
Yes - flat design.

**Comment by interduo** [comment]
Harmless but they cover succesfully any other messages before because of terminal buffer.

**Comment by interduo** [comment]
This problem affects also lqos_scheduler just look at log `journalctl -u lqos_scheduler -n1000` it should contains nothing that is not assigned with lqos_sheduler.

**Comment by rchac** [comment]
Fixed with #525

**Comment by interduo** [comment]
@rchac its fixes by only partialy (the htb trash warning), python version and empty bin is still showed when runing ./LibreQoS.py without --debug/--verbose
